name: samtools_faidx
description: Index FASTA reference file with samtools faidx
keywords:
  - fasta
  - faidx
  - samtools
  - index
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments and reference files.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence:
        - "MIT"
      identifier: biotools:samtools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'reference' ]
    - fasta:
        type: file
        description: Reference FASTA file
        pattern: "*.{fa,fasta,fna}"
        ontologies: []
output:
  fasta_fai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'reference' ]
      - fasta:
          type: file
          description: Input FASTA file
          ontologies: []
      - "*.fai":
          type: file
          description: FASTA index file
          pattern: "*.fai"
          ontologies: []
  versions_samtools:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - samtools:
          type: string
          description: The name of the tool
      - samtools version | sed '1!d;s/.* //':
          type: eval
          description: The expression to obtain the version of the tool
